CREATE DATABASE IF NOT EXISTS COMENTARIOS;

USE COMENTARIOS;

CREATE TABLE CMT_COMENTARIOS {
    cmt_id INTEGER PRIMARY KEY AUTOINCREMENT,
    cmt_nome VARCHAR(100) NOT NULL,
    cmt_email VARCHAR(100) NOT NULL,
    cmt_comentario VARCHAR(500) NOT NULL
};

CREATE USER IF NOT EXISTS 'cmtAdmin'@'localhost' IDENTIFIED BY 'PassWdAdm1n*';

GRANT ALL PRIVILEGES ON COMENTARIOS.* TO 'cmtAdmin'@'localhost';

FLUSH PRIVILEGES;



